---
title: "module4"
author: "Harrison Leduc"
date: "2024-02-25"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{module4}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette covers Unit 1 Module 4. This vignette works with the crop_ylds dataset.

1. Three tibbles
```{r, warning = FALSE, message = FALSE}
library(hjl246)
library(dplyr)

g10 <- lapply((1:10), function(x) {
    o <- paste0("G", x)
    return(o)
})
g10

g15 <- lapply((1:15), function(x) {
    o <- paste0("G", x)
    return(o)
})
g15

g20 <- lapply((1:20), function(x) {
    o <- paste0("G", x)
    return(o)
})
g20

set.seed(1)
t1 <- tibble(v1 = g10, v2 = runif(10, 75, 125))
t1

t2 <- tibble(v1 = g15, v3 = sample(LETTERS[1:6], 15, replace = TRUE))
t2

t3 <- tibble(v1 = g20, v4 = rnorm(20, mean = 100, sd = 20))
t3




joinLeft <- left_join(t1, t2, by = c("v1" = "v1")) %>% 
  left_join(., t3, by = c("v1" = "v1"))
joinLeft

joinRight <- right_join(t1, t2, by = c("v1" = "v1")) %>% 
  right_join(., t3, by = c("v1" = "v1"))
joinRight

joinFull <- full_join(t1, t2, by = c("v1" = "v1")) %>% 
  full_join(., t3, by = c("v1" = "v1"))
joinFull

joinInner <- inner_join(t1, t2, by = c("v1" = "v1")) %>% 
  inner_join(., t3, by = c("v1" = "v1"))
joinInner
```

2. Recreate crop_ylds 
```{r, warning = FALSE, message = FALSE}
library(readr)
library(dplyr)
library(tidyr)

#Chunk 1
fs <- dir(system.file("extdata/", package = "geospaar"), 
          pattern = "FAOSTAT", full.names = TRUE)
fs

l2 <- lapply(fs, function(x) {
  readr::read_csv(x) %>%
    mutate(grp = gsub(".csv", "", basename(x)))
})
l2

#Chunk 11
crop_df <- do.call(rbind, lapply(l2, function(x) {
  x %>% dplyr::select(Item, Area, Element, Year, Value) %>% 
    pivot_wider(names_from = Element, values_from = Value) %>% 
    rename(crop = Item, country = Area, year = Year, 
           harv_area = `Area harvested`, prod = Production)
}))
crop_df


#Chunk 16
yields <- crop_df %>% 
  mutate(yield = prod / harv_area) %>% 
  dplyr::select(crop, country, year, yield)
yields

crop_ylds <- left_join(x = crop_df, y = yields, 
                       by = c("crop", "country", "year"))
crop_ylds

crop_ylds <- left_join(crop_df, yields) 
crop_ylds

#Chunk 19
crop_ylds <- crop_df %>% mutate(yield = prod / harv_area)
crop_ylds

#Chunk 21
crop_ylds <- crop_ylds %>% 
  mutate(country = ifelse(country == "South Africa", "ZAF", country)) %>%  
  mutate(country = ifelse(country == "Zambia", "ZMB", country)) %>% 
  mutate(crop = tolower(crop))

set.seed(1)
crop_ylds %>% sample_n(5)
```


3. dplyr verbs
```{r, warning = FALSE, message = FALSE}

harvTop5 <- crop_ylds %>% 
  filter(crop == "maize", country == "ZAF") %>% 
  arrange(-harv_area) %>% 
  slice(1:5)
harvTop5

yieldTop5 <- crop_ylds %>% 
  filter(crop == "maize", country == "ZAF") %>% 
  arrange(-yield) %>% 
  slice(1:5)
yieldTop5
  
```

4. Mean
```{r, warning = FALSE, message = FALSE}

# Error in buildVignette with the unique() function
# workAround is my work around to this
workAround <- data.frame(crop_ylds$crop)
workAround

# dplyr approach
cropYields <- crop_ylds %>%
  group_by(crop) %>%
  summarize(mean_yield = mean(yield))
cropYields



splt_apply <- sapply(unique(workAround[,]), function(x) {
  dat <- crop_ylds[crop_ylds$crop == x, ]  
  o <- data.frame(crop = x, mean_yield = mean(dat$yield))  
})
splt_apply

```

5. Correlation Matrix
```{r, warning = FALSE, message = FALSE}

corMatrix <- crop_ylds %>% 
  group_by(crop, country) %>% 
  summarise(cor = cor(harv_area, yield)) %>% 
  arrange(-cor)
corMatrix

```

6. Scatter Plot ggplot2
```{r, warning = FALSE, message = FALSE, fig.width=4.75, fig.height=3.75, fig.align = "center"}
library(ggplot2)

crop_ylds %>% filter(crop == "maize") %>% 
  ggplot() + geom_point(aes(x = harv_area, y = yield, color = country)) +
  geom_smooth(aes(x = harv_area, y = yield, color = country), method = "lm") + 
  scale_color_manual(values = c("red", "blue")) + 
  xlab("Harvested area (ha)") + ylab("Yield (t/ha)") + 
  ggtitle("Harvested area versus yield")

```


7. Scatter Plot graphics::plot
```{r, warning = FALSE, message = FALSE, fig.width=4.75, fig.height=3.75, fig.align = "center"}

zaf_maize <- crop_ylds %>% filter(crop == "wheat" & country == "ZAF")
yl <- range(crop_ylds[crop_ylds$crop == "wheat", "yield"])
plot(yield ~ year, data = zaf_maize, pch = 16, col = "blue",
     ylim = yl, main = "South African wheat (1961-2017)", 
     xlab = "", ylab = "Yield (t/ha)")
points(yield ~ year, data = zaf_maize, pch = 16, col = "grey")
abline(lm(yield ~ year, data = zaf_maize), col = "blue")

```

8. Histogram
```{r, warning = FALSE, message = FALSE, fig.width=4.75, fig.height=3.75, fig.align = "center"}

crop_ylds %>% filter(crop == "maize", country == "ZMB") %>%
  ggplot() + geom_histogram(aes(x = yield), bins = 5, fill = "blue", col = "black") +
  ggtitle("Zambian Maize") + xlab("Yield (t/ha)") + ylab("")
?ggtitle

```
