---
title: "unit2-module1"
author: "Harrison Leduc"
date: "2024-03-11"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{unit2-module1}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(hjl246)
```

## Task 1

```{r}
roads <- st_read(system.file("extdata/roads.geojson", package = "geospaar"))
roads

districts_alb <- read_sf(system.file("extdata/districts.geojson", 
                                 package = "geospaar")) %>% 
  st_transform(x = ., crs = st_crs(roads))
districts_alb

farmers_alb <- read_csv(system.file("extdata/farmer_spatial.csv", package = "geospaar")) %>% 
  distinct(uuid, x, y, season) %>% 
  st_as_sf(x = ., coords = c("x", "y"), crs = 4326) %>%
  st_transform(x = ., crs = st_crs(roads))
farmers_alb
```

## Task 2

```{r, fig.width=6, fig.height=4, fig.align = "center"}
library(sf)

plot(districts_alb %>% st_geometry(), col = "grey", graticule = TRUE, axes = TRUE)
plot(roads, add = TRUE, col = "red", lwd = 2)
plot(farmers_alb, add = TRUE, pch = "+", size = 3, col = "blue")
```

## Task 3

```{r, fig.width=5, fig.height=6, fig.align = "center"}
ggplot() +
  geom_sf(data = districts_alb, fill = "grey") +
  geom_sf(data = roads, col = "red") +
  geom_sf(data = farmers_alb, pch = "+", size = 3, col = "blue") +
  theme_bw()
```


## Task 4

```{r, fig.width=6, fig.height=4, fig.align = "center"}
median_dist <- districts_alb %>% 
  mutate(area = as.numeric(st_area(.))) %>% 
  arrange(.$area) %>% 
  slice(length(.$area) / 2)
median_dist


par(mar = c(0, 0, 1, 0))
plot(districts_alb %>% st_geometry(), col = "grey", graticule = TRUE, axes = TRUE, main = "The median area district")
plot(st_geometry(median_dist), col = "khaki", add = TRUE)
```

## Task 5

```{r, fig.width=6, fig.height=4}
median_distp <- st_centroid(median_dist)
median_distp

closest_20farmers <- farmers_alb %>% 
  filter(season == 1) %>% 
  mutate(dist = as.numeric(st_distance(x = .$geometry, y = median_distp))) %>% 
  arrange(dist) %>% 
  slice(1:20)
closest_20farmers


par(mar = c(0, 0, 0, 0))
plot(districts_alb %>% st_geometry(), col = "grey", graticule = TRUE, axes = TRUE)
plot(st_geometry(median_dist), col = "khaki", add = TRUE)
plot(st_geometry(median_distp), pch = 16, col = "purple", add = TRUE)
plot(st_geometry(farmers_alb), pch = "+", size = 3, col = "blue", add = TRUE)
plot(st_geometry(closest_20farmers), pch = "+", size = 3, col = "red", add = TRUE)
```

## Task 6



```{r, fig.width=6, fig.height=4}
mypol <- st_polygon(list(cbind(x = c(30, 31, 31, 30, 30), 
                             y = c(-10, -10, -11, -11, -10)))) %>% 
  st_sfc() %>% 
  st_sf(crs = 4326) %>% 
  st_transform(x = ., crs = st_crs(roads))
mypol

intersect_dists <- districts_alb %>% 
  slice(st_intersects(x = mypol, y = .)[[1]])
intersect_dists


plot(districts_alb %>% st_geometry(), col = "grey", graticule = TRUE, axes = TRUE)
plot(st_geometry(intersect_dists), col = "grey40", add = TRUE)
plot(st_geometry(mypol), border = "yellow",  add = TRUE)
```

The area of the polygon in hectares 'ha' is:

```{r}
mypol_area <- mypol %>% st_area() %>% 
  units::set_units("ha")
mypol_area
```

## Task 7
```{r, fig.width=6, fig.height=4}
mypol_dist_int <- districts_alb %>% 
  slice(st_intersects(x = mypol, y = .)[[1]]) %>% 
  st_cast("MULTIPOLYGON") %>% 
  mutate(area = as.numeric(units::set_units(st_area(.), "ha")))
mypol_dist_int

plot(districts_alb %>% st_geometry(), col = "grey", graticule = TRUE, axes = TRUE)
plot(st_geometry(mypol_dist_int), col = rainbow(n = nrow(mypol_dist_int)), add = TRUE)
```

Mean and Median of the intersections (in hectares):
```{r}
summary(mypol_dist_int)[4,3]
summary(mypol_dist_int)[3,3]
```

## Task 8
```{r, fig.width=6, fig.height=4}
roads_extreme <- roads %>% 
  arrange(length(.$geometry)) 
roads_extreme

roads_extreme <- roads %>% 
  mutate(road_length = as.numeric(units::set_units(st_length(.), "km"))) %>% 
  arrange(road_length) %>% 
  slice(1, length(.$roadid))
roads_extreme


roads_extreme_buff <- st_buffer(x = roads_extreme, dist = 50000)
roads_extreme_buff

plot(districts_alb %>% st_geometry(), col = "grey", graticule = TRUE, axes = TRUE)
plot(st_geometry(roads_extreme_buff), col = "blue", add = TRUE)
plot(st_geometry(roads_extreme), lwd = 3, col = "red", add = TRUE)
```

## Task 9
```{r, fig.width=6, fig.height=4}
set.seed(2)
rand_points <- st_sample(roads_extreme_buff, size = c(10, 50), exact = TRUE)

plot(districts_alb %>% st_geometry(), col = "grey", graticule = TRUE, axes = TRUE)
plot(st_geometry(roads_extreme_buff), col = "blue", add = TRUE)
plot(st_geometry(roads_extreme), lwd = 3, col = "red", add = TRUE)
plot(rand_points, pch = 16, col = "yellow", add = TRUE)


#plot(st_sample(roads_extreme_buff, size = c(10, 50), exact = TRUE), pch = 3, col = "red", add = TRUE)
```

## Task 10

```{r, fig.width=6, fig.height=4}
roads_int <- roads %>% 
  slice(st_intersects(x = roads_extreme_buff[2, ], y = .)[[1]])
roads_int

plot(districts_alb %>% st_geometry(), col = "grey", graticule = TRUE, axes = TRUE)
plot(st_geometry(roads_extreme_buff[2, ]), col = "blue", add = TRUE)
plot(st_geometry(roads_int), col = "red", add = TRUE)
```

Total distance of intersected roads (km):

```{r}
roads_int <- roads_int %>% 
  mutate(dist = as.numeric(units::set_units(st_length(.), "km")))

sum(roads_int$dist)
```

##############################################
CHECK GEOG 246 WORD DOC
#######################################################################################################################################################################################################################################
